config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'
  resources :points,
    :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } 
  get 'about' => 'about#index'

end

app/models/point.rb
class Point < ActiveRecord::Base
	validates :pt_id, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :json
  def index
  	connection = ActiveRecord::Base.connection
	@results = ActiveRecord::Base.connection.tables
  end  
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
	def index
		Point.table_name = params[:table_name]
		@tname = params[:table_name]
		@points = Point.all
	end

	def show
		@point = Point.find(params[:id])
	end

	def new
		@point = Point.new
	end

	def create
		@point = Point.new(point_params)
		if @point.save
			redirect_to :controller => "points",:action => "index", :table_name => Point.table_name ,:notice => "Point is crerated successfully" 
		else
			render "new"
		end

	end
	def edit
		@point = Point.find(params[:id])
	end

	def update
		@point = Point.find(params[:id])
		if(@point.update_attributes(point_params))
			redirect_to :controller => "points",:action => "index", :table_name => Point.table_name ,:notice => "Point is updated successfully" 
		else
			render "edit"
		end			
	end

	def destroy
	end

	private

  	def point_params
    	params.require(:point).permit(:pt_id, :pt_type, :pt_origin, :resource_id, :init_val, :alm_enable)
  	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h3>About CLIE</h3>
<h4>(Cloud Import/Export)</h4>
<p>This application helps you to perform CRUD operations on all the points exported to cloud which can be later imported by other applications</p>

app/views/home/index.html.erb
<!-- Example row of columns -->
		
<div class="row">
  <div class="table-responsive">
     <table class="table table-hover">
  		<thead>
  				<tr>
    				<th>Tables</th>        				
  				</tr>
  		</thead>
  		<tbody>
  			<% unless @results.empty? %>
  	    <% @results.each do |tname| %>
  	      <tr>				        
  	        <td><%= link_to tname, {:controller => "points", :action => "index", :table_name => tname}%></td>		        
  	      </tr>
  	    <% end %>
  	  <% else %>
  	    <tr>
  	      <td colspan="0">Nothing to see here move along please</td>
  	    </tr>
  	  <% end %>
  		</tbody>
     </table>
  </div>
</div>    

app/views/home/list.html.erb
<b>hello from list</b>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Predix CLIE</title>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
</head>
<body>

	<nav class="navbar navbar-inverse navbar">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CLIE Points View</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        	<ul class="nav navbar-nav">
        		<li><%= link_to "Home", root_path%></li>
        		<li><%= link_to "About", about_path%></li>	
        	</ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <%= render 'partials/jumbotron' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= value%>
      <%end%>

    	<%= yield %>
      	<hr>
      	<%= render 'partials/footer' %>
    </div> <!-- /container -->
</body>
</html>

app/views/partials/_footer.html.erb
<footer>
	<p>&copy; 2015 Company </p>
</footer>

app/views/partials/_jumbotron.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<%if params[:controller]=='home'%>
	<div class="jumbotron container-fluid">
		<div class="container">
			<h1>Predix CLIE</h1>
			<p>List of all Point Tables from Database</p>
		</div>
	</div>
<%end%>

app/views/points/edit.html.erb
<div class = "page-header">
   <h1>
      Point Edit 
      <small>(edit point details and update)</small>
   </h1>   
</div>
<div class="row">
	<%= form_for @point do |p| %>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="pt_id">Point ID</label>
				<%= p.text_field :pt_id,:placeholder => "Point ID" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="pt_type">Point Type</label>
				<%= p.text_field :pt_type,:placeholder => "Point Type" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="pt_origin">Point Origin</label>
				<%= p.text_field :pt_origin,:placeholder => "Point Origin" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="resource_id">Resource ID</label>
				<%= p.text_field :resource_id,:placeholder => "Resource ID" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="init_val">Initial Value</label>
				<%= p.text_field :init_val,:placeholder => "Initial Value" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="alm_enable">Alarm Enable</label>
				<%= p.text_field :alm_enable,:placeholder => "Alarm Enable" ,:class => "form-control" %>
			</div>
		</fieldset>
		<div>
			<br/>
			<fieldset>
				<div class="col-xs-4">
					<%= p.submit "Update Point", class: "btn btn-default" %>
				</div>
			</fieldset>
		</div>
	<%end%>
</div>

app/views/points/index.html.erb
<div class = "page-header">
   <h1>
      Point Configuration 
      <small>from table</small>
   </h1>   
</div> 
<div class="row">
   <table class="table table-bordered">
      <thead>
          <tr>
            <th>Point Name</th>
            <th>Point Type</th>
            <th>Point Origin</th>
            <th>Resource ID</th>
            <th>Initial Value</th>
            <th>Alarm Enabled</th>                
          </tr>
      </thead>
      <tbody>
        <% unless @points.empty? %>
        <% @points.each do |point| %>
          <tr>            
            <td><%= link_to point.pt_id, point %></td>
            <td><%=point.pt_type%></td>
            <td><%=point.pt_origin%></td>
            <td><%=point.resource_id%></td>
            <td><%=point.init_val%></td>
            <td><%=point.alm_enable%></td>           
          </tr>
        <% end %>
        <% else %>
        <tr>
          <td colspan="0">Nothing to see here move along please</td>
        </tr>
        <% end %>           
      </tbody>
     </table> 
     <p><%= link_to "Add Point", new_point_path, class: "btn btn-default" %></p>
  </div>

app/views/points/new.html.erb
<h1>
      Point Create 
      <small>(add a new point to your configuration)</small>
   </h1>
<div class="row">
	<%= form_for @point do |p| %>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="pt_id">Point ID</label>
				<%= p.text_field :pt_id,:placeholder => "Point ID" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="pt_type">Point Type</label>
				<%= p.text_field :pt_type,:placeholder => "Point Type" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="pt_origin">Point Origin</label>
				<%= p.text_field :pt_origin,:placeholder => "Point Origin" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="resource_id">Resource ID</label>
				<%= p.text_field :resource_id,:placeholder => "Resource ID" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="init_val">Initial Value</label>
				<%= p.text_field :init_val,:placeholder => "Initial Value" ,:class => "form-control" %>
			</div>
		</fieldset>
		<fieldset>
			<br/>
			<div class="col-xs-4">
				<label for="alm_enable">Alarm Enable</label>
				<%= p.text_field :alm_enable,:placeholder => "Alarm Enable" ,:class => "form-control" %>
			</div>
		</fieldset>
		<div>
			<br/>
			<fieldset>
				<div class="col-xs-4">
					<%= p.submit "Add New Point", class: "btn btn-default" %>
				</div>
			</fieldset>
		</div>
	<%end%>
</div>

app/views/points/show.html.erb
<div class = "page-header">
   <h1>
      Point Details 
      <small>to view and edit</small>
   </h1>   
</div> 
<div class="row">
   <table class="table table-bordered">
      <thead>
          <tr>
            <th>Column Name</th>
            <th>Data</th>                           
          </tr>
      </thead>
      <tbody>
          <tr>
            <td>Point ID</td>            
            <td><%=@point.pt_id%></td>                      
          </tr>
          <tr>
            <td>Point Type</td>            
            <td><%=@point.pt_type%></td>                      
          </tr>
          <tr>
            <td>Point Origin</td>            
            <td><%=@point.pt_origin%></td>                      
          </tr>
          <tr>
            <td>Resource ID</td>            
            <td><%=@point.resource_id%></td>                      
          </tr>
          <tr>
            <td>Initial Value</td>            
            <td><%=@point.init_val%></td>                      
          </tr>
          <tr>
            <td>Alarm Enabled</td>            
            <td><%=@point.alm_enable%></td>                      
          </tr>
      </tbody>
     </table> 
     <p><%= link_to 'Edit Point', edit_point_path(@point) %></p>
  </div>